feature/added user updateProfile
posinnove/posinnove-be pull request #11
Opened 2024-07-25 08:13 UTC by kayigireerneste

2024-07-26 05:50 UTC, fabmukunzi requested changes
Great work 🎉.
Let's work on the comment and we are good togo

2024-07-26 05:50 UTC, fabmukunzi commented on src/controllers/user.controller.js
> +    }
Let's re-use checkIfEmailExists middleware

2024-07-26 06:31 UTC, fabmukunzi requested changes

2024-07-26 06:31 UTC, fabmukunzi commented on src/routes/user.routes.js
> +userRoutes.patch('/profile/updateProfile', protectRoute, upload.single('profileImage'), updateProfile);
remember to change this route as well

2024-07-29 14:46 UTC, amiparadis250 reviewed
Please address all required changes  from Fab and contact me asap , for documenting this api

2024-07-29 16:23 UTC, kayigireerneste commented
hey!
am still working on it not later than tomorrow it will be done

On Mon, Jul 29, 2024 at 4:47 PM ISHIMWE Ami Paradis <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Please address all required changes from Fab and contact me asap , for
> documenting this api
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/posinnove/posinnove-be/pull/11#pullrequestreview-2205191632>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUPLW2L7SNED5BSUFJE5DZLZOZIWZAVCNFSM6AAAAABLOAKFM6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMBVGE4TCNRTGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-30 11:12 UTC, fabmukunzi requested changes

2024-07-30 11:12 UTC, fabmukunzi commented on src/controllers/user.controller.js
> +
Why can't I update password?

2024-07-30 11:12 UTC, fabmukunzi commented on src/controllers/user.controller.js
> +
Let's use sequelize to exclude sensitive data instead of using this manual approach

2024-07-30 11:12 UTC, fabmukunzi commented on src/controllers/user.controller.js
> +
Move this to validations folder

2024-07-30 12:46 UTC, fabmukunzi requested changes

2024-07-30 12:46 UTC, fabmukunzi commented on src/controllers/user.controller.js
> +    user.password = updates.password !== undefined ? updates.password : user.password;
Let's remove simplify this logic

2024-07-30 18:53 UTC, fabmukunzi approved these changes

2024-07-30 18:53 UTC, merged